author: Scott Priestley
email: scott.priestley@gmail.com
description: MyProjects

# Essential for subfolder hosting
baseurl: "/devfolio" 
url: "https://scottpriestley.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
